Admin
MatthewOakley/CodeUSummer2018Team35 pull request #10
Opened 2018-05-24 19:46 UTC by MatthewOakley

I did some basic work of getting some of the stats on the admin page like the number of users and conversations. I was going to add test cases but worked off of previous code that has test cases built into it. Let me know if you have any questions :)

2018-05-24 23:33 UTC, erschwartz requested changes
Nice progress, Matt!

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/controller/AdminServlet.java
> +/** Getting the conversation stats for the webpage */
You don't need comments for imports, you can delete these

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/controller/AdminServlet.java
> +  /** Store class that gives access to Users. */
For single line comments like these you can use `//` style. The only time we require `/** */` style comments is for docstrings which are exclusive to classes and functions.

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/controller/AdminServlet.java
> +  /** Store class that gives access to Conversations. */
`//`

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/controller/AdminServlet.java
> +    /** This is for getting the current instance of users */
`//`

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/controller/AdminServlet.java
> +    /** This is for getting the current instance of conversations */
`//`

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/controller/AdminServlet.java
> +    setConversationStore(ConversationStore.getInstance());
A note on comments: I only recommend them when it's not immediately clear to someone reading your code what the purpose of your code is / what is going on. Here, it's pretty obvious. Therefore, I'd say it's actually better to let your code speak for itself here and delete them.

I'd go through some of your other comments as well and evaluate whether you need them. In college they'll make you comment `*everything*`, but, in reality, it's not always the case in industry.

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/controller/AdminServlet.java
> +    /** This gets the current number of users in the database*/
Space after database

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/ConversationStore.java
> +    }
Fix the spacing in this method please. Space always after () and in if statements

```java
public int getConversationAmount() {
  if (this == null) {
    return 0;
  }
}

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/UserStore.java
> +  public int getUserAmount(){
Fix spacing here please. See comment above.

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/ConversationStore.java
> +    if(this == null){
I think this check is unnecessary as you can assume that they're calling this method on an instance that is obtained/constructed via getInstance

2018-05-24 23:33 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/UserStore.java
> +    if(this == null){
See comment above

2018-05-26 16:30 UTC, StevenAb approved these changes
Apart from what Erika mentioned, this LGTM!

2018-05-30 14:40 UTC, erschwartz commented
Hi Matt, if you finished the changes for this, make sure to push them up so we can see them.

2018-05-30 18:15 UTC, erschwartz requested changes

2018-05-30 18:15 UTC, erschwartz commented on src/main/java/codeu/controller/AdminServlet.java
>    /** when user visits this sends them to admin page */
when -> When

2018-05-30 18:15 UTC, erschwartz commented on src/main/java/codeu/controller/AdminServlet.java
> +    /** This gets the current number of users in the database */
Please see the comment I made before about comments. Single line comments that are not docstrings can use // and you can delete these as they are unnecessary

2018-05-31 10:22 UTC, erschwartz approved these changes
LGTM

2018-05-31 12:59 UTC, merged