Activity feed
MatthewOakley/CodeUSummer2018Team35 pull request #12
Opened 2018-05-30 18:09 UTC by StevenAb

Here is the bulk of the MVP for the activity feed. The date stamps still need to be converted into a human readable format and sorted chronologically.

2018-05-30 18:26 UTC, erschwartz requested changes
Nice work -- Can you add unit tests for this please?

2018-05-30 18:26 UTC, erschwartz commented on src/main/java/codeu/controller/ActivityFeedServlet.java
> +    //Sets the ConversationStore used by this servlet.
Please use docstring style comments for methods.

2018-05-30 18:26 UTC, erschwartz commented on src/main/java/codeu/controller/ActivityFeedServlet.java
> +    //Sets the MessageStore used by this servlet.
Docstring

2018-05-30 18:26 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/UserStore.java
> +  //Returns a list of all user IDs
Docstring

2018-05-30 18:26 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/UserStore.java
> +    return userIds;
You can use Java 8 to do this in 1 line:

```java
return users.stream().map(User::getId).collect(Collectors.toList());
```

2018-05-30 18:26 UTC, erschwartz commented on src/main/webapp/WEB-INF/view/activity-feed.jsp
> +        if(conversations != null && !conversations.isEmpty()) {
You don't need to check if it's empty as if it is the for loop will simply never execute

2018-05-30 18:26 UTC, erschwartz commented on src/main/webapp/WEB-INF/view/activity-feed.jsp
> +                if(messages != null && !messages.isEmpty()) {
Same thing here, don't need to check if empty if it's part of for loop

2018-05-30 19:26 UTC, erschwartz commented
Recapping what we discussed in the meeting:

You'll want to make each of the classes you wish to sort implement Comparable.
Then you'll want to have a method like:
```java
@Override
public int compareTo(Conversation c) {
        return this.creationTime.compareTo(c.creationTime);
}
```

Then in the jsp or perhaps in the servlet (up to you where you think it would be better to do this) you can do
```java
conversations.sort();
```

2018-05-30 20:09 UTC, MatthewOakley approved these changes
Besides what was stated everything LGTM!

2018-06-01 16:42 UTC, erschwartz requested changes

2018-06-01 16:42 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/UserStore.java
> +    for(User user : users) {
Fix spacing here

2018-06-01 16:42 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/UserStore.java
> +    return userIds;
You missed this comment

2018-06-02 10:38 UTC, erschwartz approved these changes
LGTM, thanks

2018-06-02 14:05 UTC, merged