Hashtag
MatthewOakley/CodeUSummer2018Team35 pull request #19
Opened 2018-06-11 19:36 UTC by MatthewOakley

2018-06-13 15:26 UTC, erschwartz requested changes

2018-06-13 15:26 UTC, erschwartz commented on src/main/java/codeu/model/data/Hashtag.java
> +    messageIds.add(initialId);
I'd create the list inside of the constructor instead

2018-06-13 15:26 UTC, erschwartz commented on src/main/java/codeu/model/data/Hashtag.java
> +    if (messageIds.contains(id)) {
Perhaps you should use a set instead to avoid duplicates

2018-06-13 15:26 UTC, erschwartz commented on src/main/java/codeu/model/data/Hashtag.java
> +  /** This will return an array of the ids that are linked ot this hashtag*/
ot -> to

2018-06-13 15:26 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/HashtagStore.java
> +    hashtags.add(hashtag);
Do you want to check if a hashtag already exists?

2018-06-13 15:26 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/HashtagStore.java
> +    persistentStorageAgent.writeThrough(hashtag);
Do you want to check that this hashtag already exists and can be updated?

2018-06-13 15:26 UTC, erschwartz commented on src/main/java/codeu/model/store/persistence/PersistentDataStore.java
> +    hashtagEntity.setProperty("tagName", hashtag.getName());
Use snake case

2018-06-13 15:26 UTC, erschwartz commented on src/main/java/codeu/model/store/persistence/PersistentDataStore.java
> +    hashtagEntity.setProperty("uuidList", collection);
Snake case

2018-06-13 15:26 UTC, erschwartz commented on src/main/webapp/WEB-INF/view/hashtag.jsp
> +    Welcome to the hashtag page!
Write a to-do

2018-06-13 15:26 UTC, erschwartz commented
Sorry, forgot to press send when I was requesting changes.

2018-06-14 14:09 UTC, erschwartz requested changes
Great work Matt

Next time please split this into smaller PRs. This is too much code for one PR

2018-06-14 14:09 UTC, erschwartz commented on src/main/java/codeu/controller/ChatServlet.java
> +
Delete one of these lines

2018-06-14 14:09 UTC, erschwartz commented on src/main/java/codeu/controller/ChatServlet.java
> +        currentTag = new Hashtag(tag, messageUUID);
You never add this to the store

2018-06-14 14:09 UTC, erschwartz commented on src/main/java/codeu/controller/HashtagServlet.java
> +    System.out.println(requestUrl);
Delete

2018-06-14 14:09 UTC, erschwartz commented on src/main/java/codeu/controller/HashtagServlet.java
> +    System.out.println(tagName);
Delete

2018-06-14 14:09 UTC, erschwartz commented on src/main/java/codeu/controller/HashtagServlet.java
> +    List<Message> messages = new ArrayList<Message>();
You can use <> functionality

2018-06-14 14:09 UTC, erschwartz commented on src/main/java/codeu/controller/HashtagServlet.java
> +    }
Simplify to one line:

```java
List<Message> messages = idList.stream().map(id -> messageStore.getMessageById(Id)).collect(Collectors.toList());
```

2018-06-14 14:09 UTC, erschwartz commented on src/main/java/codeu/model/data/Hashtag.java
> +    if (messageIds.contains(id)) {
Still need to convert to set

2018-06-14 14:09 UTC, erschwartz commented on src/main/java/codeu/model/store/basic/HashtagStore.java
> +  public boolean doesHashtagExist(String name) {
I'd rename to isPresent

2018-06-14 14:09 UTC, erschwartz commented on src/main/java/codeu/model/store/persistence/PersistentDataStore.java
> +        List<UUID> messageIdsList = new ArrayList<UUID>();
```java
List<UUID> messageIDs = messagesIds.stream().map(UUID::fromString).collect(Collectors.toList());
```

As an aside, we avoid writing "list" or "map" at the end of variable names unless absolutely necessary. For lists, sets, etc. we simply make it plural (i.e. messageIds) and for maps we do x by y (messageIdsByName, for example).

2018-06-14 14:09 UTC, erschwartz commented on src/main/java/codeu/model/store/persistence/PersistentDataStore.java
> +    Entity hashtagEntity = new Entity("chat-hashtags", hashtag.getName());
Underscore not dash

2018-06-15 02:11 UTC, erschwartz requested changes
This looks excellent, thanks Matt! Just a few small changes.

2018-06-15 02:11 UTC, erschwartz commented on src/main/java/codeu/controller/HashtagServlet.java
> +
Delete

2018-06-15 02:11 UTC, erschwartz commented on src/main/java/codeu/model/data/Hashtag.java
> +    return;
Don't need return here

2018-06-15 02:11 UTC, erschwartz commented on src/main/java/codeu/model/data/Hashtag.java
> +    this.hashtag = tag.toUpperCase();
You already make it uppercase in the doPost method

2018-06-15 02:11 UTC, erschwartz commented on src/main/java/codeu/model/data/Hashtag.java
> +    this.hashtag = tag.toUpperCase();
You already make it uppercase when you originally create the tag

2018-06-15 13:40 UTC, erschwartz requested changes

2018-06-15 13:40 UTC, erschwartz commented on src/main/java/codeu/controller/HashtagServlet.java
> +
I think you should get of all of the extra spaces you add in this method. It's generally good practice to group together lines that have similar purposes. It's also a bit of an eye sore when you're reading through it.

2018-06-15 13:40 UTC, erschwartz commented on src/main/java/codeu/controller/HashtagServlet.java
> +
Never leave a blank line before a }

2018-06-15 13:40 UTC, erschwartz commented on src/main/java/codeu/model/store/persistence/PersistentDataStore.java
> +        Set<UUID> messageIds = new HashSet<UUID>();
```java
Set<UUID> messageIds = datastoreMessageIds.stream().map(id -> UUID.fromString(id)).collectors(Collectors.toSet());
```

And delete the todo

2018-06-17 19:30 UTC, ilianac requested changes

2018-06-17 19:30 UTC, ilianac commented on src/main/java/codeu/controller/ChatServlet.java
> +import java.util.ArrayList;
Can delete ArrayList import bc it has already been imported

2018-06-17 19:30 UTC, ilianac commented on src/main/java/codeu/controller/ChatServlet.java
> +
delete extra space

2018-06-17 19:30 UTC, ilianac commented on src/main/java/codeu/model/store/basic/MessageStore.java
> +
delete extra space

2018-06-17 19:30 UTC, ilianac commented on src/main/java/codeu/model/store/persistence/PersistentDataStore.java
> +
delete extra space

2018-06-18 16:47 UTC, erschwartz approved these changes
Just one small change then LGTM

2018-06-18 16:47 UTC, erschwartz commented on src/main/java/codeu/controller/ChatServlet.java
> +    Set<String> hashtags = new HashSet<String>();
Group above lines together, avoid extra spacing when not necessary for clarification

2018-06-18 23:02 UTC, ilianac approved these changes
Looks Good! :)

2018-06-19 00:02 UTC, merged