Activity Feed
MatthewOakley/CodeUSummer2018Team35 pull request #7
Opened 2018-05-22 04:42 UTC by StevenAb

Created servlet and jsp for the activity feed and updated web.xml to handle "/activityfeed" urls.

Sort of underestimated the amount of code I wrote during this session and ended up dumping the entire prototype into this PR; sorry! Will submit smaller code segments for review in the future.

Also- should we be linking our prototype pages in the navigation bars of existing jsps?

2018-05-22 05:21 UTC, erschwartz requested changes
No worries, this is perfect size.

To answer your question: I would only link the prototypes once they are in a more finished state (i.e. there are no major to-dos left).

2018-05-22 05:21 UTC, erschwartz commented on src/main/java/codeu/controller/ActivityFeedServlet.java
> +     * This function firex when a user navigates to the activity feed page.
firex -> fires

2018-05-22 05:21 UTC, erschwartz commented on src/main/java/codeu/controller/ActivityFeedServlet.java
> +            request.getRequestDispatcher("/WEB-INF/view/activityfeed.jsp").forward(request, response);
I'd rename to activity-feed.jsp

2018-05-22 05:21 UTC, erschwartz commented on src/main/webapp/WEB-INF/view/activityfeed.jsp
> +<!DOCTYPE html>
See comment about renaming this file

2018-05-22 05:21 UTC, erschwartz commented on src/main/webapp/WEB-INF/view/activityfeed.jsp
> +    <nav>
Write a to-do here please

format:
`TODO($USERNAME): Take out the trash`

2018-05-22 20:14 UTC, MatthewOakley commented on src/main/java/codeu/controller/ActivityFeedServlet.java
> +     * This function provides a common setup method for use by the test framework or servlet's init() function.
I don't know if this is just me but could you break this up into two lines so its easier to read.

2018-05-22 20:16 UTC, MatthewOakley approved these changes
This looks good to me. That little change isn't needed it just makes it easier to read.

2018-05-23 19:14 UTC, StevenAb commented
Hey, just fixed the comments, changed the filename, and added a todo!

2018-05-24 20:30 UTC, MatthewOakley approved these changes
This looks good to me!

2018-05-24 23:19 UTC, erschwartz commented
LGTM

2018-05-24 23:19 UTC, erschwartz approved these changes

2018-05-25 04:06 UTC, merged