added servlet and jsp and edited web.xml for profile pages prototype
MatthewOakley/CodeUSummer2018Team35 pull request #8
Opened 2018-05-22 22:20 UTC by asma526

Created the simple prototype by making a servlet and jsp for the profile pages. Also edited the web.xml to add the /prototype url.

2018-05-22 22:56 UTC, erschwartz requested changes
Good start, Asma!

2018-05-22 22:56 UTC, erschwartz commented on src/main/webapp/WEB-INF/web.xml
> +    <url-pattern>/profilepages</url-pattern>
I'd add a - between profile and pages

2018-05-22 22:56 UTC, erschwartz commented on src/main/webapp/WEB-INF/view/profile-pages.jsp
> +    <a href="/profilepages">Profile Pages</a>
/profile-pages according to other comment

2018-05-22 22:56 UTC, erschwartz commented on src/main/webapp/WEB-INF/view/profile-pages.jsp
> +
Please write a TO-DO here in format
`TODO($USERNAME): Take out the trash`

2018-05-24 11:58 UTC, ilianac approved these changes

2018-05-24 23:19 UTC, erschwartz commented
LGTM

2018-05-24 23:19 UTC, erschwartz approved these changes

2018-05-24 23:29 UTC, merged